# Generated by Django 5.2.17 on 2026-10-02 06:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=255)),
                ("website", models.URLField(blank=True, null=True)),
                ("industry", models.CharField(blank=True, max_length=100)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("hr_contact_name", models.CharField(blank=True, max_length=100)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=20)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InternshipWindow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("title", models.CharField(max_length=255)),
                ("min_semester", models.IntegerField(default=3)),
                (
                    "min_cgpa",
                    models.DecimalField(decimal_places=2, default=6.0, max_digits=4),
                ),
                (
                    "min_attendance_percentage",
                    models.DecimalField(decimal_places=2, default=75.0, max_digits=5),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="internship",
            name="report_file",
        ),
        migrations.AddField(
            model_name="disciplinarycase",
            name="assessment_type",
            field=models.CharField(
                choices=[
                    ("INTERNAL_EXAM", "Internal Exam"),
                    ("ASSIGNMENT", "Assignment"),
                    ("LAB_PRACTICAL", "Lab Practical"),
                    ("SEMESTER_EXAM", "Semester Exam"),
                    ("CONDUCT", "Conduct"),
                ],
                default="CONDUCT",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="disciplinarycase",
            name="case_number",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="disciplinarycase",
            name="committee_decision",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("CLEARED", "Cleared"),
                    ("MARKS_CANCELLED", "Marks Cancelled"),
                    ("SUSPENSION_YEAR_DROP", "Suspension / Year Drop"),
                ],
                default="PENDING",
                max_length=25,
            ),
        ),
        migrations.AddField(
            model_name="disciplinarycase",
            name="committee_remarks",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="disciplinarycase",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="disciplinary_cases",
                to="academics.course",
            ),
        ),
        migrations.AddField(
            model_name="disciplinarycase",
            name="evidence_file",
            field=models.FileField(
                blank=True, null=True, upload_to="disciplinary_evidence/"
            ),
        ),
        migrations.AddField(
            model_name="disciplinarycase",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="disciplinarycase",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_cases",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="internship",
            name="applied_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="internship",
            name="approved_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="internship",
            name="attendance_rating",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="internship",
            name="communication_rating",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="internship",
            name="completion_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="internship",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="internship",
            name="faculty_mentor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mentored_internships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="internship",
            name="faculty_remarks",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="internship",
            name="internship_type",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="internship",
            name="location",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="internship",
            name="problem_solving_rating",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="internship",
            name="professionalism_rating",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="internship",
            name="rejection_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="internship",
            name="supervisor_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="internship",
            name="teamwork_rating",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="internship",
            name="technical_skills_rating",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="internship",
            name="work_mode",
            field=models.CharField(
                choices=[
                    ("ONSITE", "On-site"),
                    ("REMOTE", "Remote"),
                    ("HYBRID", "Hybrid"),
                ],
                default="ONSITE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="internship",
            name="company_name",
            field=models.CharField(
                blank=True, help_text="Legacy or custom company name", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="internship",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("SUBMITTED", "Submitted"),
                    ("PENDING", "Pending Faculty Review"),
                    ("CHANGES_REQUIRED", "Changes Required"),
                    ("RESUBMITTED", "Resubmitted"),
                    ("APPROVED", "Approved"),
                    ("ASSIGNED", "Assigned by Faculty"),
                    ("ACTIVE", "Active"),
                    ("COMPLETED", "Completed"),
                    ("REJECTED", "Rejected"),
                    ("CANCELLED", "Cancelled"),
                    ("WAIVED", "Waived"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="internship",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="internships",
                to="academics.company",
            ),
        ),
        migrations.CreateModel(
            name="FacultyInternshipOpportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("role", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("required_skills", models.TextField(blank=True)),
                ("eligibility", models.TextField(blank=True)),
                ("duration_months", models.IntegerField()),
                (
                    "stipend",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("location", models.CharField(blank=True, max_length=255)),
                ("work_mode", models.CharField(default="ONSITE", max_length=20)),
                ("application_deadline", models.DateField()),
                ("available_positions", models.IntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="academics.company",
                    ),
                ),
                (
                    "faculty_creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="internship",
            name="opportunity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="applications",
                to="academics.facultyinternshipopportunity",
            ),
        ),
        migrations.CreateModel(
            name="InternalAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        choices=[
                            ("MID_1", "Mid 1"),
                            ("MID_2", "Mid 2"),
                            ("LAB_1", "Lab 1"),
                            ("LAB_2", "Lab 2"),
                            ("COMPRE", "Compre"),
                        ],
                        default="MID_1",
                        max_length=255,
                    ),
                ),
                (
                    "max_marks",
                    models.DecimalField(decimal_places=2, default=50.0, max_digits=5),
                ),
                (
                    "marks_obtained",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("weightage", models.IntegerField(default=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "Submitted"),
                            ("EVALUATED", "Evaluated"),
                            ("FLAGGED_MALPRACTICE", "Flagged Malpractice"),
                        ],
                        default="SUBMITTED",
                        max_length=20,
                    ),
                ),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="internal_assessments",
                        to="academics.course",
                    ),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="internal_assessments",
                        to="academics.enrollment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InternshipAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("action", models.CharField(max_length=50)),
                ("remarks", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "internship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="academics.internship",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InternshipDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("RESUME", "Resume/CV"),
                            ("OFFER_LETTER", "Offer Letter"),
                            ("CONFIRMATION", "Internship Confirmation Letter"),
                            ("COVER_LETTER", "Cover Letter"),
                            ("OTHER", "Other Supporting Document"),
                        ],
                        max_length=20,
                    ),
                ),
                ("file", models.FileField(upload_to="internships/documents/")),
                ("file_name", models.CharField(blank=True, max_length=255)),
                ("file_size", models.IntegerField(default=0)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "internship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="academics.internship",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CourseGradingScheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "grading_type",
                    models.CharField(
                        choices=[("ABSOLUTE", "Absolute"), ("RELATIVE", "Relative")],
                        default="RELATIVE",
                        max_length=20,
                    ),
                ),
                (
                    "mean",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "std_dev",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("FINALIZED", "Finalized (Pending Approval)"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_courses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grading_schemes",
                        to="academics.course",
                    ),
                ),
                (
                    "finalized_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="finalized_courses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("course",)},
            },
        ),
    ]
