# Generated by Django 5.2.17 on 2026-10-02 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_company_internshipwindow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='academic_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('DISCIPLINARY_HOLD', 'Disciplinary Hold'), ('DROPOUT', 'Dropout'), ('GRADUATED', 'Graduated')], default='ACTIVE', max_length=50),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='current_semester',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='current_year',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='internship_waived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='academics.program'),
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField()),
                ('section', models.CharField(blank=True, default='', max_length=10)),
                ('is_current', models.BooleanField(default=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='academics.program')),
            ],
            options={
                'ordering': ['-start_year'],
                'unique_together': {('program', 'start_year', 'end_year', 'section')},
            },
        ),
    ]
