# Generated by Django 5.2.17 on 2026-08-24 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0007_department_program"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InternshipWindow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("min_semester", models.IntegerField(default=3)),
                (
                    "min_cgpa",
                    models.DecimalField(decimal_places=2, default=6.0, max_digits=4),
                ),
                (
                    "min_attendance_percentage",
                    models.DecimalField(decimal_places=2, default=75.0, max_digits=5),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name="disciplinarycase",
            name="assessment_type",
            field=models.CharField(
                choices=[
                    ("INTERNAL_EXAM", "Internal Exam"),
                    ("ASSIGNMENT", "Assignment"),
                    ("LAB_PRACTICAL", "Lab Practical"),
                    ("SEMESTER_EXAM", "Semester Exam"),
                    ("CONDUCT", "Conduct"),
                ],
                default="CONDUCT",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="disciplinarycase",
            name="case_number",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="disciplinarycase",
            name="committee_decision",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("CLEARED", "Cleared"),
                    ("MARKS_CANCELLED", "Marks Cancelled"),
                    ("SUSPENSION_YEAR_DROP", "Suspension / Year Drop"),
                ],
                default="PENDING",
                max_length=25,
            ),
        ),
        migrations.AddField(
            model_name="disciplinarycase",
            name="committee_remarks",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="disciplinarycase",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="disciplinary_cases",
                to="academics.course",
            ),
        ),
        migrations.AddField(
            model_name="disciplinarycase",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="disciplinarycase",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_cases",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="academic_status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("DISCIPLINARY_HOLD", "Disciplinary Hold"),
                    ("SUSPENDED", "Suspended"),
                    ("DROPOUT", "Dropout"),
                    ("GRADUATED", "Graduated"),
                ],
                default="ACTIVE",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="InternalAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "max_marks",
                    models.DecimalField(decimal_places=2, default=50.0, max_digits=5),
                ),
                (
                    "marks_obtained",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("weightage", models.IntegerField(default=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "Submitted"),
                            ("EVALUATED", "Evaluated"),
                            ("FLAGGED_MALPRACTICE", "Flagged Malpractice"),
                        ],
                        default="SUBMITTED",
                        max_length=20,
                    ),
                ),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="internal_assessments",
                        to="academics.course",
                    ),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="internal_assessments",
                        to="academics.enrollment",
                    ),
                ),
            ],
        ),
    ]
