# Generated by Django 5.2.17 on 2026-08-25 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "academics",
            "0008_internshipwindow_disciplinarycase_assessment_type_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="semesterregistration",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="internship_waived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="semesterregistration",
            name="is_summer_term",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="internship",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending Approval"),
                    ("APPROVED", "Approved"),
                    ("COMPLETED", "Completed"),
                    ("REJECTED", "Rejected"),
                    ("WAIVED", "Waived"),
                ],
                default="PENDING",
                max_length=15,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="semesterregistration",
            unique_together={("enrollment", "semester", "is_summer_term")},
        ),
    ]
