# Generated by Django 5.2.17 on 2026-08-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_expand_facultyprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyprofile',
            name='alma_mater',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='facultyprofile',
            name='awards',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='facultyprofile',
            name='courses_taught',
            field=models.TextField(blank=True, help_text='Semicolon-separated list of courses'),
        ),
        migrations.AlterField(
            model_name='facultyprofile',
            name='current_project',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='facultyprofile',
            name='highest_qualification',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='facultyprofile',
            name='linkedin',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='facultyprofile',
            name='office_room',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='facultyprofile',
            name='orcid_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='facultyprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='facultyprofile',
            name='sample_publication_venues',
            field=models.TextField(blank=True, help_text='Semicolon-separated venues'),
        ),
        migrations.AlterField(
            model_name='facultyprofile',
            name='specialization',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
