# Generated by Django 5.2.17 on 2026-08-29 11:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0009_alter_semesterregistration_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="disciplinarycase",
            name="evidence_file",
            field=models.FileField(
                blank=True, null=True, upload_to="disciplinary_evidence/"
            ),
        ),
    ]
