# Generated by Django 5.2.17 on 2026-08-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_alter_facultyprofile_alma_mater_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyprofile',
            name='additional_roles',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
