# Generated by Django 5.2.17 on 2026-09-04 02:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_facultyprofile_additional_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField(blank=True, null=True)),
                ('institutional_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('personal_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('alternate_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile_no', models.CharField(blank=True, max_length=15, null=True)),
                ('alternate_mobile_no', models.CharField(blank=True, max_length=15, null=True)),
                ('sip_mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('skype_id', models.CharField(blank=True, max_length=100, null=True)),
                ('birth_place', models.CharField(blank=True, max_length=100, null=True)),
                ('native_place', models.CharField(blank=True, max_length=100, null=True)),
                ('home_town', models.CharField(blank=True, max_length=100, null=True)),
                ('home_state', models.CharField(blank=True, max_length=100, null=True)),
                ('permanent_address', models.TextField(blank=True, null=True)),
                ('permanent_city', models.CharField(blank=True, max_length=100, null=True)),
                ('permanent_state', models.CharField(blank=True, max_length=100, null=True)),
                ('permanent_pin', models.CharField(blank=True, max_length=20, null=True)),
                ('present_address', models.TextField(blank=True, null=True)),
                ('present_city', models.CharField(blank=True, max_length=100, null=True)),
                ('present_state', models.CharField(blank=True, max_length=100, null=True)),
                ('present_pin', models.CharField(blank=True, max_length=20, null=True)),
                ('objective', models.TextField(blank=True, null=True)),
                ('experience', models.TextField(blank=True, null=True)),
                ('qualifications', models.TextField(blank=True, null=True)),
                ('computer_proficiency', models.TextField(blank=True, null=True)),
                ('awards_achievements', models.TextField(blank=True, null=True)),
                ('extra_curricular_interests', models.TextField(blank=True, null=True)),
                ('mis', models.TextField(blank=True, null=True)),
                ('languages_known', models.CharField(blank=True, max_length=255, null=True)),
                ('specialisation', models.CharField(blank=True, max_length=255, null=True)),
                ('specialisation_ii', models.CharField(blank=True, max_length=255, null=True)),
                ('minor', models.CharField(blank=True, max_length=255, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='student_photos/')),
                ('enrollment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profile', to='academics.enrollment')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
