# Generated by Django 5.2.17 on 2026-08-29 14:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0011_alter_internalassessment_title_coursegradingscheme"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("website", models.URLField(blank=True, null=True)),
                ("industry", models.CharField(blank=True, max_length=100)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("hr_contact_name", models.CharField(blank=True, max_length=100)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name="internship",
            name="applied_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="internship",
            name="approved_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="internship",
            name="attendance_rating",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="internship",
            name="communication_rating",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="internship",
            name="completion_certificate",
            field=models.FileField(
                blank=True, null=True, upload_to="internships/certificates/"
            ),
        ),
        migrations.AddField(
            model_name="internship",
            name="completion_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="internship",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="internship",
            name="faculty_mentor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mentored_internships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="internship",
            name="faculty_remarks",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="internship",
            name="internship_type",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="internship",
            name="joining_letter",
            field=models.FileField(
                blank=True, null=True, upload_to="internships/joining/"
            ),
        ),
        migrations.AddField(
            model_name="internship",
            name="location",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="internship",
            name="offer_letter",
            field=models.FileField(
                blank=True, null=True, upload_to="internships/offers/"
            ),
        ),
        migrations.AddField(
            model_name="internship",
            name="problem_solving_rating",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="internship",
            name="professionalism_rating",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="internship",
            name="rejection_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="internship",
            name="supervisor_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="internship",
            name="teamwork_rating",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="internship",
            name="technical_skills_rating",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="internship",
            name="work_mode",
            field=models.CharField(
                choices=[
                    ("ONSITE", "On-site"),
                    ("REMOTE", "Remote"),
                    ("HYBRID", "Hybrid"),
                ],
                default="ONSITE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="internship",
            name="company_name",
            field=models.CharField(
                help_text="Legacy or custom company name", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="internship",
            name="report_file",
            field=models.FileField(
                blank=True, null=True, upload_to="internships/reports/"
            ),
        ),
        migrations.AlterField(
            model_name="internship",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending Approval"),
                    ("APPROVED", "Approved"),
                    ("ACTIVE", "Active"),
                    ("COMPLETED", "Completed"),
                    ("REJECTED", "Rejected"),
                    ("CANCELLED", "Cancelled"),
                    ("WAIVED", "Waived"),
                ],
                default="PENDING",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="internship",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="internships",
                to="academics.company",
            ),
        ),
        migrations.CreateModel(
            name="InternshipAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=50)),
                ("remarks", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "internship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="academics.internship",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
