# Generated by Django 5.2.17 on 2026-08-29 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0012_company_internship_applied_date_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="internship",
            name="completion_certificate",
        ),
        migrations.RemoveField(
            model_name="internship",
            name="joining_letter",
        ),
        migrations.RemoveField(
            model_name="internship",
            name="offer_letter",
        ),
        migrations.RemoveField(
            model_name="internship",
            name="report_file",
        ),
        migrations.AlterField(
            model_name="internship",
            name="company_name",
            field=models.CharField(
                blank=True, help_text="Legacy or custom company name", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="internship",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("SUBMITTED", "Submitted"),
                    ("PENDING", "Pending Faculty Review"),
                    ("CHANGES_REQUIRED", "Changes Required"),
                    ("RESUBMITTED", "Resubmitted"),
                    ("APPROVED", "Approved"),
                    ("ACTIVE", "Active"),
                    ("COMPLETED", "Completed"),
                    ("REJECTED", "Rejected"),
                    ("CANCELLED", "Cancelled"),
                    ("WAIVED", "Waived"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="FacultyInternshipOpportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("required_skills", models.TextField(blank=True)),
                ("eligibility", models.TextField(blank=True)),
                ("duration_months", models.IntegerField()),
                (
                    "stipend",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("location", models.CharField(blank=True, max_length=255)),
                ("work_mode", models.CharField(default="ONSITE", max_length=20)),
                ("application_deadline", models.DateField()),
                ("available_positions", models.IntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="academics.company",
                    ),
                ),
                (
                    "faculty_creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="internship",
            name="opportunity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="applications",
                to="academics.facultyinternshipopportunity",
            ),
        ),
        migrations.CreateModel(
            name="InternshipDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("RESUME", "Resume/CV"),
                            ("OFFER_LETTER", "Offer Letter"),
                            ("CONFIRMATION", "Internship Confirmation Letter"),
                            ("COVER_LETTER", "Cover Letter"),
                            ("OTHER", "Other Supporting Document"),
                        ],
                        max_length=20,
                    ),
                ),
                ("file", models.FileField(upload_to="internships/documents/")),
                ("file_name", models.CharField(blank=True, max_length=255)),
                ("file_size", models.IntegerField(default=0)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "internship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="academics.internship",
                    ),
                ),
            ],
        ),
    ]
