# Generated by Django 5.2.17 on 2026-09-05 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0013_studentprofile_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyprofile',
            name='about',
            field=models.TextField(blank=True, help_text='Short bio or about text'),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='faculty_enrollment_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='institutional_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='facultyprofile',
            name='admin_role',
            field=models.CharField(choices=[('None', 'None'), ('Head of Department', 'Head of Department'), ('Dean', 'Dean'), ('Exam Controller', 'Exam Controller'), ('Warden', 'Warden'), ('Hostel Warden', 'Hostel Warden'), ('Mess Incharge', 'Mess Incharge'), ('Finance Officer', 'Finance Officer'), ('Placement Coordinator', 'Placement Coordinator'), ('Lab In-charge', 'Lab In-charge'), ('Sports Coordinator', 'Sports Coordinator'), ('Cultural Coordinator', 'Cultural Coordinator'), ('Library Incharge', 'Library Incharge'), ('Transport Incharge', 'Transport Incharge')], default='None', max_length=50),
        ),
    ]
