# Generated by Django 5.2.17 on 2026-09-14 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('application_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('entry_type', models.CharField(choices=[('ONLINE', 'Online Regular'), ('OFFLINE', 'Offline/Paper Application'), ('LATERAL', 'Lateral Entry Yr2'), ('TRANSFER', 'Transfer Student'), ('DIRECT', 'Direct Admission')], default='ONLINE', max_length=15)),
                ('tenth_school_name', models.CharField(blank=True, max_length=255)),
                ('tenth_board', models.CharField(blank=True, max_length=100)),
                ('tenth_passing_year', models.IntegerField(blank=True, null=True)),
                ('tenth_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('twelfth_school_name', models.CharField(blank=True, max_length=255)),
                ('twelfth_board', models.CharField(blank=True, max_length=100)),
                ('twelfth_passing_year', models.IntegerField(blank=True, null=True)),
                ('twelfth_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('extra_curricular_achievements', models.TextField(blank=True)),
                ('any_gap_years', models.BooleanField(default=False)),
                ('scholarship_requested', models.BooleanField(default=False)),
                ('interview_date', models.DateTimeField(blank=True, null=True)),
                ('interviewer_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('INTERVIEW_SCHEDULED', 'Interview Scheduled'), ('INTERVIEW_PASSED', 'Interview Passed (Eligible)'), ('INTERVIEW_FAILED', 'Interview Failed (Not Eligible)'), ('SELECTED', 'Selected for Admission'), ('REJECTED', 'Rejected'), ('FEE_PENDING', 'Fee Pending'), ('ENROLLED', 'Enrolled')], default='DRAFT', max_length=20)),
                ('enrollment_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('applied_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApplicantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('father_name', models.CharField(blank=True, max_length=255)),
                ('mother_name', models.CharField(blank=True, max_length=255)),
                ('guardian_name', models.CharField(blank=True, max_length=255)),
                ('guardian_occupation', models.CharField(blank=True, max_length=255)),
                ('family_income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('category', models.CharField(choices=[('GEN', 'General'), ('SC', 'SC'), ('ST', 'ST'), ('OBC', 'OBC'), ('OTHER', 'Other')], default='GEN', max_length=10)),
                ('blood_group', models.CharField(blank=True, max_length=5)),
                ('nationality', models.CharField(default='Indian', max_length=50)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('permanent_address', models.TextField(blank=True)),
                ('correspondence_address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('document_name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='documents/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('VERIFIED', 'Verified'), ('FORGED', 'Forged/Rejected')], default='PENDING', max_length=15)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField()),
                ('concession_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('status', models.CharField(choices=[('APPLIED', 'Applied'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='APPLIED', max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SeatAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('allocated_department', models.CharField(max_length=100)),
                ('allocated_program', models.CharField(max_length=100)),
                ('allocated_batch', models.CharField(max_length=100)),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
