# Generated by Django 5.2.17 on 2026-08-11 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('REGULAR', 'Regular'), ('LATERAL', 'Lateral Entry Yr2')], default='REGULAR', max_length=15)),
                ('previous_school_name', models.CharField(max_length=255)),
                ('exam_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Entrance Exam/Review'), ('SELECTED', 'Selected'), ('REJECTED', 'Rejected')], default='PENDING', max_length=15)),
                ('applied_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admission_application', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
