# Generated by Django 5.2.17 on 2026-08-11 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='documents/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('VERIFIED', 'Verified'), ('FORGED', 'Forged/Rejected')], default='PENDING', max_length=15)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='admission.admissionapplication')),
            ],
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('concession_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('status', models.CharField(choices=[('APPLIED', 'Applied'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='APPLIED', max_length=15)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scholarship', to='admission.admissionapplication')),
            ],
        ),
    ]
