# Generated by Django 5.2.17 on 2026-08-14 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0002_document_scholarship'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='admissionapplication',
            old_name='exam_score',
            new_name='previous_marks_percentage',
        ),
        migrations.RemoveField(
            model_name='admissionapplication',
            name='user',
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='application_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='interview_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='interviewer_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='scholarship_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='admissionapplication',
            name='entry_type',
            field=models.CharField(choices=[('ONLINE', 'Online Regular'), ('OFFLINE', 'Offline/Paper Application'), ('LATERAL', 'Lateral Entry Yr2'), ('TRANSFER', 'Transfer Student'), ('DIRECT', 'Direct Admission')], default='ONLINE', max_length=15),
        ),
        migrations.AlterField(
            model_name='admissionapplication',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('INTERVIEW_SCHEDULED', 'Interview Scheduled'), ('SELECTED', 'Selected for Admission'), ('REJECTED', 'Rejected'), ('FEE_PENDING', 'Fee Pending'), ('ENROLLED', 'Enrolled')], default='DRAFT', max_length=20),
        ),
        migrations.CreateModel(
            name='ApplicantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('father_name', models.CharField(blank=True, max_length=255)),
                ('mother_name', models.CharField(blank=True, max_length=255)),
                ('family_income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='admission.applicantprofile'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SeatAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_department', models.CharField(max_length=100)),
                ('allocated_program', models.CharField(max_length=100)),
                ('allocated_batch', models.CharField(max_length=100)),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
                ('allocated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seat_allocation', to='admission.admissionapplication')),
            ],
        ),
    ]
