# Generated by Django 5.2.17 on 2026-08-14 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0003_rename_exam_score_admissionapplication_previous_marks_percentage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionapplication',
            name='interviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interviews_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='admissionapplication',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('INTERVIEW_SCHEDULED', 'Interview Scheduled'), ('INTERVIEW_PASSED', 'Interview Passed (Eligible)'), ('INTERVIEW_FAILED', 'Interview Failed (Not Eligible)'), ('SELECTED', 'Selected for Admission'), ('REJECTED', 'Rejected'), ('FEE_PENDING', 'Fee Pending'), ('ENROLLED', 'Enrolled')], default='DRAFT', max_length=20),
        ),
    ]
