# Generated by Django 5.2.17 on 2026-08-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0004_admissionapplication_interviewer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionapplication',
            name='enrollment_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
