# Generated by Django 5.2.17 on 2026-08-16 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_department_program'),
        ('admission', '0005_admissionapplication_enrollment_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionapplication',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='academics.program'),
        ),
    ]
