# Generated by Django 5.2.17 on 2026-08-13 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_parent_user_university_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='user',
            name='university_email',
        ),
    ]
