# Generated by Django 5.2.17 on 2026-08-13 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('PROSPECTIVE_STUDENT', 'Prospective Student'), ('STUDENT', 'Student'), ('FACULTY', 'Faculty'), ('ADMIN', 'Admin'), ('PARENT', 'Parent'), ('HOD', 'Head of Department'), ('COMMITTEE', 'Disciplinary Committee')], default='PROSPECTIVE_STUDENT', max_length=25),
        ),
    ]
