# Generated by Django 5.2.17 on 2026-09-05 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_additional_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dark_mode',
            field=models.BooleanField(default=False),
        ),
    ]
